// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Cart() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Cart Drawer Backdrop --><div id=\"cart-backdrop\" class=\"fixed inset-0 bg-black/50 z-[60] hidden\"></div><!-- Cart Drawer --><div id=\"cart-drawer\" class=\"fixed top-0 right-0 h-full w-full sm:w-96 bg-background border-l border-foreground/20 shadow-2xl z-[70] translate-x-full transition-transform duration-300 ease-in-out flex flex-col\"><!-- Header --><div class=\"flex items-center justify-between p-4 border-b border-foreground/20\"><h2 class=\"font-serif text-xl font-bold tracking-wide uppercase\">Your Cart</h2><button id=\"cart-close\" class=\"p-2 hover:text-primary transition-colors\" aria-label=\"Close cart\"><svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div><!-- Body (scrollable) --><div id=\"cart-items\" class=\"grow overflow-y-auto p-4\"><p class=\"text-muted-foreground text-center py-8\">Loading...</p></div><!-- Footer --><div id=\"cart-footer\" class=\"border-t border-foreground/20 p-4 hidden\"><div class=\"flex justify-between items-center mb-1\"><span class=\"font-serif font-bold text-lg\">Total:</span> <span id=\"cart-total\" class=\"font-serif font-bold text-lg\"></span></div><p class=\"text-xs text-muted-foreground mb-4\">+ $1.00 processing fee at checkout</p><a href=\"/checkout\" class=\"block w-full py-3 px-8 bg-primary text-primary-foreground font-display uppercase tracking-widest border-2 border-primary hover:bg-background hover:text-primary transition-all duration-300 text-sm text-center\">Proceed to Checkout</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
