FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

RUN apk add --no-cache ca-certificates curl

# Download Tailwind CLI
RUN curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.8/tailwindcss-linux-x64-musl \
    && chmod +x tailwindcss-linux-x64-musl \
    && mv tailwindcss-linux-x64-musl /usr/local/bin/tailwindcss

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["sh", "-c", "tailwindcss -i static/input.css -o static/style.css --watch & air -c .air.toml"]
